name: dart_chassis_forge
description: TODO
version: 0.0.1
homepage: https://github.com/axrs/dart_chassis_forge
repository: https://github.com/axrs/dart_chassis_forge.git
issue_tracker: https://github.com/axrs/dart_chassis_forge/issues
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_rucksack:
    git:
      url: https://github.com/axrs/dart_rucksack.git
      ref: 0.0.1
  get_it: ^7.2.0
  glob: ^2.0.2
  logging: ^1.0.2
  process_run: ^0.12.2+1
  reflectable: ^3.0.0
  smart_arg:
    git:
      url: https://github.com/axrs/smart_arg.git
      ref: master

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
