name: chassis_forge
description: Chassis Forge is a foundation for building modern CLI apps and tools to help with project automation and other various tasks.
version: 1.0.1
homepage: https://github.com/axrs/dart_chassis_forge
repository: https://github.com/axrs/dart_chassis_forge.git
issue_tracker: https://github.com/axrs/dart_chassis_forge/issues
documentation: https://axrs.github.io/dart_chassis_forge/doc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  rucksack: ^0.0.1
  get_it: ^7.2.0
  glob: ^2.0.2
  logging: ^1.0.2
  path: ^1.8.0
  process_run: ^0.12.2+1
  reflectable: ^3.0.4
  smart_arg_fork: ^2.1.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
